config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:index, :show, :update] do
    get 'letter', to: 'events#letter'
    post 'mail', to: 'events#mail'
    resources :comments
  end
  resources :leases, only: [:new, :index]

  devise_for :users
  root to: 'pages#home'

  get 'urgent_events', to: 'events#index_urgent'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_accordion.html.erb
<!-- <p>
  <a data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    <p id = "accordion-decoration">Envoi notification au locataire <i class="fa fa-envelope" aria-hidden="true"></i></p>
  </a>
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-block">
    <ul>Congé avec renouvellement</ul>
    <ul>Congé refus de renouvellement (motif grave)</ul>
    <ul>Congé refus de renouvellement (insalubrité)</ul>
    <ul>Congé refus de renouvellement (avec indemnité)</ul>
  </div>
</div>
 -->

app/views/shared/_button_status.html.erb
<div class = "status-update col-xs-12 col-md-8 col-md-offset-2">
<% if @event.description == "fin de bail" || @event.description == "révision de loyer"%>
    <% if @event.status == "owner_to_contact"%>
    <!-- BTN OWNER TO CONTACT -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
    Contacter le bailleur
    </button>
    <% elsif (@event.status == "owner_contacted") || (@event.status == "tenant_to_notify") %>
    <!-- BTN OWNER CONTACTED -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
    Notifier le locataire
    </button>
    <% elsif (@event.status == "tenant_notified") %>
    <p>Cet évenement a déjà été traité</p>
    <% else %>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
    Contacter le bailleur
    </button>
    <% end %>
  <% elsif @event.description == "retard loyer" %>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
    Notifier le locataire
    </button>
  <% end %>
</div>

app/views/shared/_checkbox_forms.html.erb
<div class="flexbox-checkbox col-xs-8 col-xs-offset-2">
  <div class="flexbox-checkbox-item">
    <div class="col-xs-12">
      <div class = "flexbox-subcheckbox">
        <div>
          <%= check_box_tag :late_rent, params[:late_rent], @late_rent_checked, class: "checkbox-input fancy-checkbox" %>
          <%= label_tag :late_rent%>
        </div>
        <p> Retard de loyer (<%= @late_rent.length %>) </p>
      </div>
    </div>
  </div>

  <div class="flexbox-checkbox-item">
    <div class="col-xs-12">
      <div class = "flexbox-subcheckbox">
        <div>
          <%= check_box_tag :end_of_lease, params[:end_of_lease], @end_of_lease_checked, class: "checkbox-input fancy-checkbox" %>
          <%= label_tag :end_of_lease%>
        </div>
        <p>Fin de bail (<%= @end_of_lease.length %>) </p>
      </div>
    </div>
  </div>

  <div class="flexbox-checkbox-item">
    <div class="col-xs-12">
      <div class = "flexbox-subcheckbox">
        <div>
          <%= check_box_tag :rent_revision, params[:rent_revision], @rent_revision_checked, class: "checkbox-input fancy-checkbox" %>
          <%= label_tag :rent_revision %>
        </div>
        <p>Révision de loyer (<%= @rent_revision.length %>)</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_comment.html.erb
<div class="col-xs-12 comment-structure">
    <% comments.each do |comment| %>
    <tr>
      <td><p id = comment-line><img src="https://kitt.lewagon.com/placeholder/users/florentlienard" class="avatar-comment" > - <%= current_user.first_name %> - <%= comment.created_at.strftime("%d/%m/%Y à %Hh%M") %></p></td>
      <td ><%=comment.content%></td>
      </tr>
<!--     </div> -->
      <% end %>
    </div>

app/views/shared/_email_owner_contact.html.erb
<% start_date = @event.lease.end_date - 9.years %>
<% new_rent = 0 %>
<% i = 1 %>
<% while new_rent == 0 do %>
  <% if Indice.find(i).app_date < start_date %>
      <% new_rent = ((Indice.find(1).indice / Indice.find(i-1).indice) * @event.lease.monthly_rent).round %>
  <% end %>
  <% i += 1 %>
  <% new_rent = ((Indice.find(1).indice / Indice.find(i-1).indice) * @event.lease.monthly_rent).round if i == 41  %>
<% end %>
Madame, Monsieur, <%= @event.lease.owner_name %>

Nous vous contactons au sujet de votre bien situé au <%= @event.lease.tenant_address.capitalize %> (lot #<%= @event.lease.num_lot %>), dont le bail arrive à échéance le <%= "#{@event.lease.end_date.day}/#{@event.lease.end_date.month}/#{@event.lease.end_date.year}" %>.
Le locataire doit être notifié de votre décision avant le <%= "#{@event.end_date.day}/#{@event.end_date.month}/#{@event.end_date.year}" %> (dernier délai).

Plusieurs choix se posent à vous:

  (i) le congé avec refus de renouvellement, auquel cas le locataire aura 3 mois pour prendre congé (une indemnité d'éviction sera à régler, si vous choisissez cette option nous vous présenterons le mode de calcul et les différentes implications).

  (ii) le congé avec offre de renouvellement, auquel cas le bail sera renouveller et il vous sera possible de fixer le montant du nouveau loyer.

En cas de choix de l'option (ii), merci de nous indiquer le loyer que vous souhaitez appliquer, étant donnée que sur la base de l'indice de reférence nous vous conseillons un loyer de <%= number_with_delimiter(new_rent, :delimeter => " ").to_s.gsub(',',' ') %> €.

Nous vous remercions de nous répondre dans les plus brefs délais et en tout état de cause avant le <%= @event.end_date.to_date %>.

Je reste bien entendu à votre disposition pour tout renseignement complémentaire,

Bien cordialement,

<%= current_user.first_name + " " + current_user.last_name %>

app/views/shared/_mailfordemo.html.erb
<div class="modal fade" id="mailfordemo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog latemodal" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Merci d'entrer vos coordonnées ci-dessous
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id='closecross'>
        <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="demoform">
        <div class="modal-body">
          <form>
            <div class="form-group">
              <label for="exampleInputEmail1">Votre mail:</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="nom@mail.com">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Votre nom/le nom de votre société:</label>
              <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Century 21">
            </div>
            <div class="form-group">
              <label for="exampleInputnbr">Votre téléphone:</label>
              <input type="text" class="form-control" id="exampleInputnbr" placeholder="06 85 00 00 34">
            </div>
            <button type="submit" class="formbt btn btn-primary">Être recontacté pour une démo</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_choice_late_rent.html.erb
<% @event.status == 'tenant_to_notify' ? (dest = 'locataire') : (dest = 'bailleur') %>

<div class="modal fade" id="ModalLate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog latemodal" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          <%= "Retard loyer: relancer le locataire" %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id='closecross'>
        <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="laterent modal-body">
        <div class="infolate">
          <p><i class="fa fa-info-circle"></i> La mise en demeure constitue le point de départ des intérêts de retard.</p>
        </div>
        <div class="sending-choices">
          <button class="btn btn-primary latechoice" data-toggle='modal' data-target="#exampleModalLong" data-dismiss="modal">Relance simple</button>
          <button class="btn btn-primary latechoice">Mise en demeure</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_choice_owner.html.erb
<!-- Modal calculation -->
<% start_date = @event.lease.end_date - 9.years %>
<% new_rent = 0 %>
<% i = 1 %>
<% while new_rent == 0 do %>
  <% if Indice.find(i).app_date < start_date %>
      <% new_rent = ((Indice.find(1).indice / Indice.find(i-1).indice) * @event.lease.monthly_rent).round %>
  <% end %>
  <% i += 1 %>
  <% new_rent = ((Indice.find(1).indice / Indice.find(i-1).indice) * @event.lease.monthly_rent).round if i == 41  %>
<% end %>

<!-- HTML -->
<div class="modal fade" id="Modalchoice" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="choice_owner modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          <%= "Fin de bail: notification du locataire" %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id='closecrosschoice'>
        <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <!-- etape decision bailleur -->

        <!-- etape choix loyer -->
        <div>
          <div class="content-choice row">
            <div class="instructions">
              <div class="column_info-1">
                <p><strong><i class="icon-modale fa fa-user" aria-hidden="true"></i>
 Bailleur</strong> : <%= @event.lease.owner_name%></p>
                <p><strong><i class="icon-modale fa fa-user-o" aria-hidden="true"></i> Locataire</strong> : <%= @event.lease.tenant_first_name %> <%=@event.lease.tenant_name%></p>
                <p><strong><i class="icon-modale fa fa-calendar-times-o" aria-hidden="true"></i>
 Date d'échéance</strong> : <%= @event.end_date.strftime("%d/%m/%Y") %></p>
              </div>
              <div class="column_info-2">
                <p><strong><i class="icon-modale fa fa-location-arrow" aria-hidden="true"></i>
 Adresse</strong> : <%= @event.lease.tenant_address%></p>
                <p><i class="icon-modale fa fa-key" aria-hidden="true"></i>
<strong>N° de lot</strong> : <%= @event.lease.num_lot %></p>
                <p><strong><i class="icon-modale fa fa-file-text-o" aria-hidden="true"></i> Nature du bail</strong> : <%= @event.lease.nature %></p>
              </div>
            </div>

            <!-- Form for owner choice -->
              <div class="ownerchoice rightform col-xs-12">
                <p class = "text-center"><strong>Quel est le choix de <%= @event.lease.owner_name%> ?</strong></p>
                <div class="options">
                  <div class="option option-column-1"></i><p>Renouvellement</p></div>
                  <div class="option option-column-2"><p>Refus</p></div>
                </div>
              </div>
            </div>
              <!-- OTHER MODAL -->
              <div class="rightform col-xs-12 hide" id="newrent-choice">
                <div class="step"><i class="fa fa-arrow-left"></i> Retour décision bailleur</div>
                <%= simple_form_for @event, remote: true do |e| %>
                <p><i class="fa fa-money"></i> Ancien loyer mensuel du bail: <%= number_with_delimiter(@event.lease.monthly_rent, :delimeter => " ").to_s.gsub(',',' ') %>€</p>
                <p><i class="fa fa-money"></i> Nouveau loyer proposé au bailleur: <strong><%= number_with_delimiter(new_rent, :delimeter => " ").to_s.gsub(',',' ') %>€</strong>*</p>
                  <label for="event[new_rent]">Nouveau loyer demandé par le bailleur:</label>
                  <input class="form-control numeric integer optional" type="number" step="1" name="event[new_rent]" id="event_new_rent" placeholder="<%= number_with_delimiter(new_rent, :delimeter => '').to_s.gsub(',',' ') %>">
                  <br>
                <%= e.submit "Valider nouveau loyer", class: "btn btn-primary"  %>
                  <p class="asterisque">*Nouveau loyer calculé selon l'indice des loyers commerciaux</p>
                <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  const tohideC = document.getElementsByClassName("ownerchoice")[0]
  const toshowC = document.getElementById("newrent-choice")
  const buttonback = document.getElementsByClassName('step')[0];
  const buttonoption = document.getElementsByClassName('option')[0];

  buttonoption.addEventListener("click", function () {
    tohideC.classList.add("hide");
    toshowC.classList.remove("hide");
  });

  buttonback.addEventListener("click", function () {
    toshowC.classList.add("hide");
    tohideC.classList.remove("hide");
  });
</script>

app/views/shared/_modal_owner_to_contact.erb
<% @event.status == 'tenant_to_notify' ? (dest = 'locataire') : (dest = 'bailleur') %>

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          <%= "Envoi au #{dest}" %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id='closecross'>
        <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="mail-form hide">
          <%= form_tag event_mail_path(@event) do %>
          <%#<form>%>
            <div class="form-group">
              <label for="exampleInputEmail1">
              <p></p>
                <%= "Mail à envoyer à #{@event.lease.owner_email}" %>
              </label>
              <textarea class="form-control" id="exampleTextarea" rows="3" name= "response" placeholder="Cher monsieur, nous vous contactons pour informer que votre bail                                                (...)"></textarea>
              <small id="emailHelp" class="form-text text-muted">Modifiez le mail ci-dessus si besoin puis envoyez.</small>
            </div>
        <%= submit_tag "Envoyer au #{dest}", class: 'btn btn-primary' %>
        <%# link_to "Envoyer au #{dest}", event_mail_path(@event), class: 'btn btn-primary', type: "submit" %>
          <% end %>
          <%#</form>%>
        </div>

        <div class="sending-choices">
          <%= link_to "#", class: 'choice-link' do %>
          <div class="sending-choice text-center" id="maillink">
            <h1 class="mail">Contacter par mail</h1>
            <i class="mail fa fa-envelope" aria-hidden="true"></i>
          </div>
          <% end %>
          <hr>
          <%= link_to "#{@event.id}/letter.pdf", class: 'choice-link', target: 'blank' do %>
          <div class="sending-choice pdf text-center" id='letterlink'>
            <h1 class="pdf">Générer une lettre</h1>
            <i class="pdf fa fa-file-pdf-o" aria-hidden="true"></i>
          </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<script>
  const tohide = document.getElementsByClassName("sending-choices")[0]
  const toshow = document.getElementsByClassName("mail-form")[0]
  const buttonMail = document.getElementById('maillink');
  const buttonLetter = document.getElementById('letterlink');

  buttonMail.addEventListener("click", function () {
    tohide.classList.add("hide");
    toshow.classList.remove("hide");
  });

  buttonLetter.addEventListener("click", function () {
    $("#closecross").click();
  });
</script>

app/views/shared/_modal_owner_to_contact.html.erb
<% @event.status == 'tenant_to_notify' ? (dest = 'locataire') : (dest = 'bailleur') %>

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          Choisir mode d'envoi
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id='closecross'>
        <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="mail-form hide">
          <%= form_tag event_mail_path(@event) do %>
            <div class="form-group">
              <label for="exampleInputEmail1" class="labelmail">
              <p></p>
                <strong>Mail à envoyer à : </strong><%= @event.lease.owner_email %>
              <p></p>
                <strong>Sujet : </strong> <%= "Lot #{@event.lease.num_lot} - #{@event.lease.tenant_address.capitalize} - #{@event.description.capitalize}" %>
              <p></p>
              </label>
              <textarea class="form-control" id="exampleTextarea" rows="3" name= "response" > <%= render '/shared/email_owner_contact' %> </textarea>
              <small id="emailHelp" class="form-text text-muted">Modifiez le mail ci-dessus si besoin puis envoyez.</small>
            </div>
            <%= submit_tag "Envoyer au #{dest}", class: 'btn btn-primary', id: "mail-envoye" %>
            <% end %>
        </div>

        <div class="sending-choices">
          <%= link_to "#", class: 'choice-link' do %>
          <div class="sending-choice text-center" id="maillink">
            <h1 class="mail">Contacter par mail</h1>
            <i class="mail fa fa-envelope" aria-hidden="true"></i>
          </div>
          <% end %>
          <hr>
          <%= link_to "#{@event.id}/letter.pdf", class: 'choice-link', target: 'blank' do %>
          <div class="sending-choice pdf text-center" id='letterlink'>
            <h1 class="pdf">Générer une lettre</h1>
            <i class="pdf fa fa-file-pdf-o" aria-hidden="true"></i>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  const tohide = document.getElementsByClassName("sending-choices")[0]
  const toshow = document.getElementsByClassName("mail-form")[0]
  const buttonMail = document.getElementById('maillink');
  const buttonLetter = document.getElementById('letterlink');
  const buttonSendMail = document.getElementById('mail-envoye');

  buttonMail.addEventListener("click", function () {
    tohide.classList.add("hide");
    toshow.classList.remove("hide");
  });

  buttonLetter.addEventListener("click", function () {
    $("#closecross").click();
    $('#ModalSuccess').modal('show');
    $('#TitleSuccess').text("Votre lettre a bien été générée!");
  });

    buttonSendMail.addEventListener("click", function () {
    $("#closecross").click();
    $('#ModalSuccess').modal('show');
    $('#TitleSuccess').text("Votre mail a bien été envoyé!");
  });

</script>

<%#script previously made to transform placeholder in real input
  const text = document.getElementById('exampleTextarea');
  text.addEventListener("click", function () {
    event.target.innerHTML = "Cher monsieur, nous vous contactons pour informer que votre bail                                                (...)";
  });
%>

app/views/shared/_modal_success.html.erb
<% @event.status == 'tenant_to_notify' ? (dest = 'locataire') : (dest = 'bailleur') %>
<% dest == 'locataire' ? (com = @event.com_tenant) : (com = @event.com_owner) %>

<div class="modal fade" id="ModalSuccess" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header header-success">
        <div class="headercontent">
          <%= image_tag 'success.png' %>
          <h5 id="TitleSuccess"></h5>
        </div>
      </div>

      <div class="modal-body">

        <div class="success-choices">
          <%= link_to events_path, class: 'choice-link' do %>
          <div class="success-choice text-center" id="maillink">
            <h1 class="back">Liste des évènements</h1>
            <i class="back fa fa-arrow-left" aria-hidden="true"></i>
          </div>
          <% end %>
          <hr>
          <%= link_to event_path(@event), class: 'choice-link' do %>
          <div class="success-choice pdf text-center" id='letterlink'>
            <h1 class="show">Retour à l'évènement</h1>
            <i class="show fa fa-refresh" aria-hidden="true"></i>
          </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<div class="navbar-wagon">
<div class = "left-nav-bar navbar-features">
      <!-- Home -->
      <div class="event-nav-bar">
          <%= link_to events_path, class: 'navbar-wagon-item navbar-wagon-link', id: 'events' do %>
                <div class="first-row">
                    <span class = "name-tab">Évenements</span>
                </div>
          <% end %>
      </div>
      <div class="lease-nav-bar">
        <%= link_to leases_path, class: 'navbar-wagon-item navbar-wagon-link', id: 'leases' do %>
        <div class="first-row">
          <span class = "name-tab">Contrats</span>
        </div>
        <% end %>
      </div>
    </div>
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img width="115" height="54" src="<%= image_path "leasy_logo_blue.png"%>">
  </a>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Profile picture with dropdown list -->

     <div class="search-bar-div">
      <%= form_tag events_path, method: :get do %>
      <%=  search_field_tag 'search', params[:search], class: "search-bar", placeholder: "Rechercher un propriétaire" %>
          <i class='fa fa-search', type='submit', style="color: rgb(220,220,220)"></i>
    <% end %>
    </div>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/florentlienard" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profil</a></li>
          <li> <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete%> </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Profil</a></li>
        <li><a href="#">Messages</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- Second nav bar -->
<script>
const zone = document.getElementsByClassName("navbar-features")[0];
zone.querySelectorAll("a").forEach((a) => {
// a.addEventListener("click", (event) => {
let url = window.location.href;
if (url.match(/\/event/) !== null | url.match(/\/urgent_events/) !== null) {
document.getElementById('events').classList.add("navbar-active");
} else if (url.match(/\/lease/) !== null) {
document.getElementById('leases').classList.add("navbar-active");
} else {
document.getElementById('home').classList.add("navbar-active");
}
});
</script>

app/views/shared/_status_task_list.html.erb
<% if @event.description == "fin de bail" || @event.description == "révision de loyer"%>
        <!-- OWNER TO CONTACT -->
          <% if  @event.status == "owner_to_contact"%>
             <div class = "status-box">
              <div class = "picto_status">
                <%= link_to image_tag("owner_to_be_contacted.png", :width => 100, :height => 100) %>
                <button type="button" class = "btn btn-primary status_title_black" data-toggle='modal' data-target='#exampleModalLong'>Envoyer la demande au bailleur</button>
               </div>
               <div>
                 <%= image_tag("arrow_grey.png", :width => 50, :height => 50) %>
               </div>
              <div class = "picto_status">
                <%= link_to image_tag("notify_tenant_color.png", :width => 100, :height => 100) %>
                <p class = "status_title_grey">Notifier le locataire</p>
               </div>
             </div>
          <!-- OWNER CONTACTED -->
             <% elsif (@event.status == "owner_contacted") || (@event.status == "tenant_to_notify")%>
             <div class = "status-box">
              <div class = "picto_status">
                <%= image_tag("owner_contacted.png", :width => 100, :height => 92) %>
                <p class = "status_title_grey text-center"><i class="fa fa-check-circle-o" aria-hidden="true"></i> Demande envoyée au bailleur</p>
               </div>
               <div>
                 <%= image_tag("arrow_grey.png", :width => 50, :height => 50) %>
               </div>
              <div class = "picto_status">
                <%= link_to image_tag("notify_tenant_color.png", :width => 92, :height => 100) %>
                <button type="button" class="btn btn-primary status_title_black" data-toggle="modal" data-target="#Modalchoice">Notifier le locataire</button>
               </div>
             </div>
          <!-- TENANT NOTIFIED -->
        <% elsif @event.status == "tenant_notified"%>
        <div>
            <div class = "status-box">
              <div class = "picto_status">
                <%= image_tag("owner_contacted.png", :width => 100, :height => 92) %>
                <p class = "status_title_grey text-center"><i class="fa fa-check-circle-o" aria-hidden="true"></i> La demande a été envoyée au bailleur</p>
               </div>
               <div>
                 <%= image_tag("arrow_grey.png", :width => 50, :height => 50) %>
               </div>
              <div class = "picto_status">
                <%= image_tag("notify_tenant_done.png", :width => 92, :height => 100) %>
                <p class = "status_title_grey"><i class="fa fa-check-circle-o" aria-hidden="true"></i> Le locataire a été notifié</p>
               </div>
             </div>
             <p class = "status_conclusion text-center"><strong>Félicitations, vous avez effectué l'ensemble des tâches relatives à cet évenement !</strong></p>
        </div>

          <!-- CASE WHERE STATUS UNKNOWN -->
          <% else %>
            <div class = "status-box">
              <div class = "picto_status">
                <%= link_to image_tag("owner_to_be_contacted.png", :width => 100, :height => 100) %>
                <p class = "status_title_black text-center"><i class="fa fa-check-circle-o" aria-hidden="true"></i> Demande envoyée au bailleur</p>
               </div>
               <div>
                 <%= image_tag("arrow_grey.png", :width => 50, :height => 50) %>
               </div>
              <div class = "picto_status">
                <%= link_to image_tag("notify_tenant_color.png", :width => 92, :height => 100) %>
                <p class = "status_title_black">Notifier le locataire</p>
               </div>
             </div>
          <% end %>
  <% elsif @event.description == "retard loyer" %>
    <% if  @event.status == "tenant_to_notify"%>
            <div class = "status-box">
              <div class = "picto_status">
                <%= link_to image_tag("notify_tenant_color.png", :width => 92, :height => 100) %>
                <button class = "btn btn-primary status_title_black" data-toggle='modal' data-target='#ModalLate'>Notifier le locataire</button>
               </div>
             </div>
    <% elsif @event.status == "tenant_notified"%>
                        <div class = "status-box">
            <div class = "picto_status">
              <%= image_tag("notify_tenant_done.png", :width => 92, :height => 100) %>
              <p class = "status_title_grey"><i class="fa fa-check-circle-o" aria-hidden="true"></i> Le locataire a été notifié</p>
             </div>
           </div>
    <% end %>
  <% end %>

app/views/shared/_step_1_modal.html.erb
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= link_to "Envoyer", event_owner_contacted_path(@event) %>
      </div>
    </div>
  </div>
</div>