config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:index, :show, :update] do
    get 'letter', to: 'events#letter'
    post 'mail', to: 'events#mail'
    resources :comments
  end
  resources :leases, only: [:new, :index]

  devise_for :users
  root to: 'pages#home'

  get 'urgent_events', to: 'events#index_urgent'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :lease
  has_many :comments
  STATUSES = ["owner_to_contact", "owner_contacted", "tenant_to_notify", "tenant_notified"]
  validates :status, presence: true, inclusion: {in: STATUSES}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   before_action :set_event, only: [:show, :update]

  def index
    @total_events = Event.all.to_a.delete_if {|event| !event.to_do }
    @urgent_events = Event.where("emergency_level = ?", "urgent").to_a.delete_if {|event| !event.to_do }
    @late_rent = Event.where("description = ?", "retard loyer").to_a.delete_if {|event| !event.to_do }
    @end_of_lease = Event.where("description = ?", "fin de bail").to_a.delete_if {|event| !event.to_do }
    @rent_revision = Event.where("description = ?", "révision de loyer").to_a.delete_if {|event| !event.to_do }
    @events=[]
    landing = true
    # Add a condition if you come from searchbar
    unless params[:search].blank?
      @total_events.each do |event|
        @events << event if event.lease.owner_name.downcase.include?(params[:search].downcase)
      end
    else
      # Create a hash with the params and the human redable corresponding value
      new_hash = {"late_rent" => "retard loyer", "end_of_lease" => "fin de bail", "rent_revision" => "révision de loyer"}
      # Iterate on hash to add the events ot the @events array if they are selected
      new_hash.each do |key, value|
        if params[key.to_sym] == "on"
          # Add a condition to check if the emergency level is urgent
          @events << Event.where("description = ?", value).to_a.delete_if {|event| !event.to_do }
          @events = @events.flatten
          landing = false
        end
      end
        # Return all events if nothin is selected and check if emergency level is urgent
      if @events == [] && !params.values.include?("on")
        @events = @total_events
      end
    end

    # adding some code to have checkbox's checked = true directly and adapt afterwards
    if landing && !params.values.include?("on")
      @late_rent_checked = true
      @end_of_lease_checked = true
      @rent_revision_checked = true
    else
      params[:late_rent] == "on" ? @late_rent_checked = true : @late_rent_checked = false
      params[:end_of_lease] == "on" ? @end_of_lease_checked = true : @end_of_lease_checked = false
      params[:rent_revision] == "on" ? @rent_revision_checked = true : @rent_revision_checked = false
    end

    # sorting the events array
    pivot = @events
    @events = pivot.sort_by {|event| [event.end_date, event.lease.rent_balance]}

    respond_to do |format|
      format.html
      format.js
    end
  end

  def index_urgent
    @total_events = Event.all.to_a.delete_if {|event| !event.to_do }
    @urgent_events = Event.where("emergency_level = ?", "urgent").to_a.delete_if {|event| !event.to_do }
    @late_rent = Event.where("description = ? AND emergency_level = ?", "retard loyer", "urgent").to_a.delete_if {|event| !event.to_do }
    @end_of_lease = Event.where("description = ? AND emergency_level = ?", "fin de bail", "urgent").to_a.delete_if {|event| !event.to_do }
    @rent_revision = Event.where("description = ? AND emergency_level = ?", "révision de loyer", "urgent").to_a.delete_if {|event| !event.to_do }
    # Create a hash with the params and the human redable corresponding value
    new_hash = {"late_rent" => "retard loyer", "end_of_lease" => "fin de bail", "rent_revision" => "révision de loyer"}
    @events=[]
    landing = true

    # Iterate on hash to add the events ot the @events array if they are selected
    new_hash.each do |key, value|
      if params[key.to_sym] == "on"
        # Add a condition to check if the emergency level is urgent
        @events << Event.where("description = ? AND emergency_level = ?", value, "urgent").to_a.delete_if {|event| !event.to_do }
        @events = @events.flatten
        landing = false
      end
    end
      # Return all events if nothin is selected and check if emergency level is urgent
    if @events == [] && !params.values.include?("on")
      @events = @urgent_events
    end

    # adding some code to have checkbox's checked = true directly and adapt afterwards
    if landing && !params.values.include?("on")
      @late_rent_checked = true
      @end_of_lease_checked = true
      @rent_revision_checked = true
    else
      params[:late_rent] == "on" ? @late_rent_checked = true : @late_rent_checked = false
      params[:end_of_lease] == "on" ? @end_of_lease_checked = true : @end_of_lease_checked = false
      params[:rent_revision] == "on" ? @rent_revision_checked = true : @rent_revision_checked = false
    end

    # sorting the events array
    pivot = @events
    @events = pivot.sort_by {|event| [event.end_date, event.lease.rent_balance]}

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @event.update(new_rent: params[:event][:new_rent].to_i)
    respond_to do |format|
      format.html do
        render :show
      end
      format.js
    end
  end



  def show
    @comment = Comment.new
  end

  def letter
    @event = Event.find(params[:event_id])
    respond_to do |format|
      format.pdf do
        render pdf: "letter", disposition: "attachment"
      end
    end
    if @event.status == 'owner_to_contact'
      @event.update(status: 'tenant_to_notify', com_owner: "lettre")
    else
      @event.update(status: 'tenant_notified', to_do: false, com_tenant: "lettre")
    end
  end

  def mail
    @event = Event.find(params[:event_id])
    # Instruction to get params and fill it in a new mail instance and send it
    if @event.status == 'owner_to_contact'
      EventMailer.notify_owner(@event, params[:response]).deliver_now
      @event.update(status: 'owner_contacted', com_owner: "mail")
    else
      EventMailer.notify_tenant(@event, params[:response]).deliver_now
      @event.update(status: 'tenant_notified', to_do: false, com_tenant: "mail")
    end
  end

  def home
  end

  private
  def set_event
     @event = Event.find(params[:id])
  end
end

app/views/events/_events.html.erb
<div class="container container-white">
  <table class="table table-hover background-transparent" style = "background-color: white;">
    <thead class = "table-head-event-index">
      <tr class = "table-head-event-index">
        <th style = "width: 50px;" class = "table-head-event-index">PRIORITE</th>
        <th style = "width: 150px;" class = "table-head-event-index">DESCRIPTION</th>
        <th style = "width: 150px;" class = "table-head-event-index">DEADLINE</th>
        <th style = "width: 200px;" class = "table-head-event-index">LOCATAIRE</th>
        <th style = "width: 240px;" class = "table-head-event-index">ADRESSE</th>
        <th class = "table-head-event-index" style = "width: 200px;">NATURE</th>
        <th class = "table-head-event-index" style = "width: 100px;">LOYER (€/m)</th>
        <th style = "width: 200px;" class = "table-head-event-index">BAILLEUR</th>
      </tr>
    </thead>
    <tbody>
    <% events.each do |event| %>
        <tr class = "table-row-event-index" id="<%= event.id %>">
          <td>
            <% if event.emergency_level == "non-due" %>
            <%= image_tag("Low.png", :width => 33, :height => 15) %>
            <% elsif event.emergency_level == "due" %>
            <%= image_tag("Middle.png", :width => 33, :height => 15) %>
            <% elsif event.emergency_level == "overdue"%>
            <%= image_tag("triangle.png", :width => 20, :height => 20, :class => align="center")%>
            <% else %>
            <%= image_tag("High.png", :width => 33, :height => 15) %>
            <% end %>
          </td>
          <td> <%= event.description.capitalize %> </td>
          <% date = event.end_date.to_date - Date.today%>
          <td>
            <%= event.description == "retard loyer" || event.description == "révision de loyer" ? "ns" : number_with_delimiter(date.to_i, :delimeter => " ").to_s.gsub(',',' ') + " jours" %>
          </td>
          <td> <%= event.lease.tenant_name %> </td>
          <td> <%= event.lease.tenant_address+
           " (lot ##{event.lease.num_lot})" %> </td>
          <td> <%= event.lease.nature %> </td>
          <td> <%= number_with_delimiter(event.lease.monthly_rent, :delimeter => " ").to_s.gsub(',', ' ') %> € </td>
          <td> <%= event.lease.owner_name %> </td>
        </tr>
        <tr class="spacer">
          <td class = "col_spacer" colspan="8"></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/events/index.html.erb
<%=  render 'shared/nav_bar_index' %>

<div class="spacer-checkboxes">
</div>
<%= form_tag events_path, method: :get, remote: true, id: "filter-form" do %>
<%= render 'shared/checkbox_forms' %>
<% end %>
<div class="spacer-checkboxes-1">
</div>

<div id="events-container">
  <%= render "events", events: @events %>
</div>

<% if Rails.env.production? %>
  <script>
  var turnObjToArray = function(obj) {
    return [].map.call(obj, function(element) {
      return element;
    })
  };

  var intermediary = document.querySelectorAll('.table-row-event-index');

  var linkedRows = turnObjToArray(intermediary)

  if (linkedRows.length > 0) {
    linkedRows.forEach((row) => {
      row.addEventListener("click", function() {
      window.location.href=`http://www.get-leasy.com/events/${event.target.parentNode.id}`;
      });
    })
  }
  </script>
<% else %>
  <script>
  var turnObjToArray = function(obj) {
    return [].map.call(obj, function(element) {
      return element;
    })
  };

  var intermediary = document.querySelectorAll('.table-row-event-index');

  var linkedRows = turnObjToArray(intermediary)

  if (linkedRows.length > 0) {
    linkedRows.forEach((row) => {
      row.addEventListener("click", function() {
      window.location.href=`http://localhost:3000/events/${event.target.parentNode.id}`;
      });
    })
  }
  </script>
<%end%>

app/views/events/index.js.erb
document.getElementById("events-container").innerHTML = '<%= j render "events", events: @events %>';

// selectionner la div .events
// innerHTML(<%= j render "events", events: @events %>)

app/views/events/index_urgent.html.erb
<%=  render 'shared/nav_bar_index' %>

<%= form_tag urgent_events_path, method: :get, remote: true, id: "filter-form" do %>
<div class="spacer-checkboxes">
</div>
<%= render 'shared/checkbox_forms' %>
<% end %>
<div class="spacer-checkboxes-1">
</div>

<div id="events-container">
  <%= render "events", events: @events %>
</div>



<% if Rails.env.production? %>
  <script>
  var turnObjToArray = function(obj) {
    return [].map.call(obj, function(element) {
      return element;
    })
  };

  var intermediary = document.querySelectorAll('.table-row-event-index');

  var linkedRows = turnObjToArray(intermediary)

  if (linkedRows.length > 0) {
    linkedRows.forEach((row) => {
      row.addEventListener("click", function() {
      window.location.href=`http://www.get-leasy.com/events/${event.target.parentNode.id}`;
      });
    })
  }
  </script>
<% else %>
  <script>
  var turnObjToArray = function(obj) {
    return [].map.call(obj, function(element) {
      return element;
    })
  };

  var intermediary = document.querySelectorAll('.table-row-event-index');

  var linkedRows = turnObjToArray(intermediary)

  if (linkedRows.length > 0) {
    linkedRows.forEach((row) => {
      row.addEventListener("click", function() {
      window.location.href=`http://localhost:3000/events/${event.target.parentNode.id}`;
      });
    })
  }
  </script>
<%end%>

app/views/events/letter.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <%= wicked_pdf_stylesheet_link_tag 'application' %>
  </head>


  <body>
  <div class="letterstyle">

    <!-- header -->

    <div class="letterhead">
      <div class="letterhead-left">
        <%= wicked_pdf_image_tag('logo_client.png', class: 'imageletter') %>
        <p><strong>IMMO 3000</strong></p>
        <p>16 rue des plantes</p>
        <p>75002 PARIS</p>
        <p><%= "#{current_user.first_name} #{current_user.last_name}" %></p>
        <p><%= current_user.position %> </p>
      </div>

      <div class="letterhead-right">
        <p><%= "#{@event.lease.tenant_first_name} #{@event.lease.tenant_name}" %></p>
        <p><%=  @event.lease.tenant_address%></p>
        <p>75017 PARIS</p>
        <br>
        <br>
        <br>
        <p>Paris, le <%= Date.today %> </p>
      </div>
    </div>

    <!-- content -->
    <div class="lettercontent">
      <% case @event.description %>
        <% when 'fin de bail' %>
        <%= render 'events/letters/conge_renouv' %>
        <% when 'retard loyer' %>
        <%= render 'events/letters/relance_retard' %>
      <% end %>
    </div>

    <!-- footer -->
    <div class="letterfooter">
      <%= wicked_pdf_image_tag 'signature.png' %>
    </div>

  </div>
  </body>
</html>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="stakeholders col-xs-12 col-md-4">
    <!-- PROPRIETAIRE -->
      <div class="stakeholder">
        <p id = "left-event-title"><strong><i class="icon-show fa fa-user" aria-hidden="true"></i> PROPRIÉTAIRE</strong></p>
        <p><strong>Nom :</strong> <%= @event.lease.owner_name %></p>
        <p><strong>Email : </strong><%= @event.lease.owner_email %></p>
      </div>
      <!-- BIEN -->
      <div class="stakeholder">
        <p id = "left-event-title"><strong><i class=" icon-show fa fa-home" aria-hidden="true"></i>BIEN</strong></p>
        <p><strong>Adresse :</strong> <%= @event.lease.tenant_address %></p>
        <p><strong>Nature du bail :</strong> <%= @event.lease.nature %></p>
        <p><strong>N° du lot :</strong> <%= @event.lease.num_lot %></p>
        <p><strong>Loyer mensuel :</strong> <%= number_with_delimiter(@event.lease.monthly_rent, :delimeter => " ").to_s.gsub(',',' ') %> €</p>
      </div>
      <!-- END BIEN -->
      <!-- LOCATAIRE -->
      <div class="stakeholder">
        <p id = "left-event-title"><strong><i class="icon-show fa fa-user-o" aria-hidden="true"></i>LOCATAIRE</strong></p>
        <% if (@event.lease.nature == "Commercial 3 ans") || (@event.lease.nature == "Commercial 9 ans")%>
        <p>Société : <%= @event.lease.tenant_name %> </p>
        <% else %>
        <p>Nom : <%= @event.lease.tenant_name %> </p>
        <p>Prénom : <%= @event.lease.tenant_first_name %></p>
        <% end %>
      </div>
    </div>
    <!-- END LEFT DIV -->

    <!-- RIGHT DIV -->
    <div class="lease-informations col-xs-12 col-md-7">
        <!-- EVENT DESCRIPTION -->
        <div class = "top-show-right">
        <% if (@event.description == "fin de bail")%>
        <p id = "type_event_bail"> <%= @event.description.capitalize %> </p>
        <% elsif (@event.description == "révision de loyer")%>
        <p id = "type_event_loyer"><%= @event.description.capitalize %> </p>
        <% else %>
        <p id = "type_event_paiement"><%= @event.description.capitalize %> </p>
        <% end %>
          <div class = "icon-status">
            <% if @event.emergency_level == "non-due" %>
            <%= image_tag("Low.png", :width => 40, :height => 18) %>
            <% elsif @event.emergency_level == "due" %>
            <%= image_tag("Middle.png", :width => 40, :height => 18) %>
            <% elsif @event.emergency_level == "overdue"%>
            <%= image_tag("triangle.png", :width => 20, :height => 20, :class => align="center")%>
            <% else %>
            <%= image_tag("High.png", :width => 40, :height => 18) %>
            <% end %>
          </div>
        </div>
          <!-- END TOP -->
      <div class="event-element col-xs-12">
      <% if @event.description == "retard loyer" %>
        <p id = "event-title"><strong><i class="icon-show fa fa-exclamation-circle" aria-hidden="true"></i> IMPAYÉ</strong></p>
        <p><%= number_with_delimiter(@event.lease.rent_balance, :delimeter => " ").to_s.gsub(',',' ')%> €</p>
        <% else %>
                <p id = "event-title"><strong><i class="icon-show fa fa-calendar-times-o" aria-hidden="true"></i> DATE D'ÉCHÉANCE</strong></p>
        <p><%= @event.end_date.strftime("%d/%m/%Y") %></p>
      <% end %>
      </div>
      <!-- STATUS -->
      <div class="event-element col-xs-12">
      <% if @event.description == 'retard loyer' %>
        <% if  @event.status == "tenant_to_notify"%>
          <p  id = "event-title"> <strong><i class="icon-show fa fa-list-ul" aria-hidden="true"></i> TÂCHES (0/1) :</strong></p>
        <% else %>
          <p  id = "event-title"> <strong><i class="icon-show fa fa-list-ul" aria-hidden="true"></i> TÂCHES (1/1) :</strong></p>
        <% end %>
      <% else %>
        <% if  @event.status == "owner_to_contact"%>
         <p  id = "event-title"> <strong><i class="icon-show fa fa-list-ul" aria-hidden="true"></i> TÂCHES (0/2) :</strong></p>
          <% elsif @event.status == "owner_contacted" || @event.status == "tenant_to_notify" %>
          <p  id = "event-title"> <strong><i class="icon-show fa fa-list-ul" aria-hidden="true"></i>TÂCHES  (1/2) </strong></p>
          <% elsif @event.status == "tenant_notified"%>
          <p  id = "event-title"> <strong><i class="icon-show fa fa-list-ul" aria-hidden="true"></i>TÂCHES (2/2) :</strong> </p>
        <% end %>
      <% end %>
        <%= render 'shared/status_task_list' %>
        </div>
        <div class = form-box>
        <%= render 'shared/form' %>
        <% if  !@event.comments.blank?%>
          <%= render 'shared/comment', comments: @event.comments.reverse %>
          <% else %>
          <p id = no-comment-yet>Il n'y a pas encore de commentaire sur cet évenement</p>
        <% end %>
        </div>
      </div>
    </div>
  </div>


<%= render '/shared/modal_choice_owner' %>
<%= render '/shared/modal_owner_to_contact' %>
<%= render '/shared/modal_success' %>
<% if @event.description == 'retard loyer' %>
  <%= render '/shared/modal_choice_late_rent' %>
<% end %>

app/views/events/update.js.erb
$('#exampleModalLong').modal('show');
$("#closecrosschoice").click();